tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "shivammathur/php"
brew "libidn2"
brew "php", restart_service: true
brew "composer", link: false
brew "dnsmasq"
brew "git"
brew "mysql", restart_service: true
brew "nginx", restart_service: true
brew "node"
brew "php@8.0"
brew "redis", restart_service: true
brew "starship", link: false
cask "brave-browser"
cask "canva"
cask "discord"
cask "firefox"
cask "figma"
cask "github"
cask "google-chrome"
cask "google-drive"
cask "grammarly-desktop"
cask "insomnia"
cask "iterm2"
cask "linear-linear"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "ngrok"
cask "notion"
cask "phpstorm"
cask "postman"
cask "raycast"
cask "slack"
cask "telegram-desktop"
cask "tradingview"
cask "visual-studio-code"
cask "whatsapp"
cask "zeplin"
cask "zoom"
