tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "shivammathur/php"
brew "libidn2"
brew "pcre2"
brew "php", restart_service: true
brew "composer"
brew "dnsmasq"
brew "git"
brew "mackup"
brew "mysql", restart_service: true
brew "nginx", restart_service: true
brew "node"
brew "php@8.0"
brew "php@8.1"
brew "python@3.8"
brew "redis", restart_service: true
brew "starship"
brew "yarn"
cask "brave-browser"
cask "figma"
cask "firefox"
cask "font-fira-code"
cask "github"
cask "google-chrome"
cask "google-drive"
cask "grammarly-desktop"
cask "insomnia"
cask "iterm2"
cask "linear-linear"
cask "ngrok"
cask "notion"
cask "postman"
cask "raycast"
cask "slack"
cask "tableplus"
cask "telegram-desktop"
cask "visual-studio-code"
cask "warp"
cask "zeplin"
cask "zoom"
